networks:
  net-artour:
    name: net-artour
    external: true

services:
  artour-app:
    container_name: artour-app
    image: artour-app:1.0.0
    restart: always
    networks:
        - net-artour
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.artour-app.rule=Host(`app-artour-lampung.web.id`)"
      - "traefik.http.routers.artour-app.entrypoints=websecure"
      - "traefik.http.routers.artour-app.tls.certresolver=resolver"
      - "traefik.http.services.artour-app.loadbalancer.server.port=4173"
    environment:
      - VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}
      - VITE_APP_GOOGLE_AUTH_CLIENT_ID=${VITE_APP_GOOGLE_AUTH_CLIENT_ID}
      - VITE_APP_GOOGLE_MAPS_API_KEY=${VITE_APP_GOOGLE_MAPS_API_KEY}
      - VITE_APP_TEST_MODE=${VITE_APP_TEST_MODE}